### ISSUE TITLE
Sending requests to the cluster.

### ISSUE THREAD

**Issue by abhishekgupta-1** [abhishekgupta-1/CloudHaoma#10]
Presently requests are sent to node 1 and forwarded to the leader node from there. Service will go down if node 1 goes down.

**Comment by vidhiJain** [comment]
Can we send the requests to the router process?

**Comment by abhishekgupta-1** [comment]
Requests are always sent to router process.

**Comment by vidhiJain** [comment]
Now, Router assigns it to each cluster server in round robin.
