### ISSUE TITLE
Data Sharding

### ISSUE THREAD

**Issue by abhishekgupta-1** [abhishekgupta-1/CloudHaoma#15]
Instead of replicating data across all nodes we should use data sharding technique.

**Comment by sra-013** [comment]
How is sharding different from having a replication factor of say three on
a cluster of five machines?



‌

**Comment by abhishekgupta-1** [comment]
Raft replicates the logs on all the nodes of the cluster => So if we run a single Raft instance for our cluster, we can't achieve a replication factor less than that of cluster size => Cluster should be divided into groups(shards) and raft instance should run for that group.

Some consensus algorithms support  [partial replication](http://www.tutorialride.com/distributed-databases/data-replication-in-distributed-system.htm) in which we can control which data will replicated and its replication factor. Raft doesn't support it so we should shard our data to get decrease replication factor. Also, sharding improves writes throughput.

**Comment by abhishekgupta-1** [comment]
Sharding Done #26
